config/routes.rb
Rails.application.routes.draw do


  root 'demo#index' #root route to homepage

  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages do
    member do
      get :delete
    end
  end

  get 'demo/index'
  get 'demo/hello'
  get 'demo/other_hello'
  get 'demo/google'

  #default route
  #may go away in future versions of Rails
  # get ':controller(/:action(/:id))'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord

  # self.table_name="admin_users"
  has_and_belongs_to_many :pages
  has_many :section_edits
  has_many :sections, :through => :section_edits

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord

  has_many :sections
  belongs_to :subject  #belongs_to = foreing key
  has_and_belongs_to_many :admin_users




end

app/models/section.rb
class Section < ApplicationRecord
 belongs_to :page
 has_many :section_edits
 has_many :admin_users, :through => :section_edits
end

app/models/section_edit.rb
class SectionEdit < ApplicationRecord
  belongs_to :admin_user
  belongs_to :section
end

app/models/subject.rb
class Subject < ApplicationRecord

  has_many :pages

  scope :visible, lambda {where(:visible=>true)}
  scope :invisible, lambda {where(:visible=>false)}
  scope :sorted, lambda {order("name ASC")}
  scope :newest_first, lambda{order("created_at DESC")}
  scope :search, lambda {|query| where(["name LIKE ?", "%#{(query)}%"])}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController

  layout false

  def index
    render ('index')
  end

  def hello
    @array = [1,2,3,4,5]
    @id=params['id']
    @page=params[:page]
    render ('hello')
  end

  def other_hello
    redirect_to(:action=>'hello')
  end
  def google
    redirect_to('http://google.com')

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @pages=Page.all
  end

  def show
    @page=Page.find(params[:id])
  end

  def new
    @page=Page.new({:subject_id=>"1"})
  end

  def create
    @page=Page.new(page_params)
    if @page.save
      flash[:notice]="Page created"
      redirect_to(pages_path)
    else
      render('new')
    end
  end

  def edit
    @page=Page.find(params[:id])
  end

  def update
    @page=Page.find(params[:id])
    if @page.update_attributes(page_params)
      flash[:notice]="Page updated"
      redirect_to(page_path(@page))
    else
      render('edit')
    end
  end

  def delete
    @page=Page.find(params[:id])
  end

  def destroy
    @page=Page.find(params[:id])
    @page.destroy
    flash[:notice]="Page '#{@page.name}' destroyed"
  end
private
  def page_params
    params.require(:page).permit(:name,:position,:description,:subject_id)

  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def index
    @subjects = Subject.all# Subject.order / Subject.sorted (wykorzystanie scope)
  end

  def show
    @subject = Subject.find(params[:id])
  end

  def new
    @subject = Subject.new({:name => "default"})
  end

  def create
    #Instantiate a new object using form parameters
    @subject=Subject.new(subject_params)
    # Save the object
    if @subject.save
    # If save succeeds, redirect t othe index action
      flash[:notice]="Subject created successfully."
      redirect_to(subjects_path)
    else
    # If safe fails, redisplay the form so user can fix problems
      render('new')
    end
  end

  def edit
    @subject = Subject.find(params[:id])
  end

  def update
    #Find a new object using form parameters
    @subject = Subject.find(params[:id])
    # Save the object
    if @subject.update_attributes(subject_params)
    # If save succeeds, redirect t othe show action
    flash[:notice]="Subject updated successfully."
      redirect_to(subject_path(@subject))
    else
    # If safe fails, redisplay the form so user can fix problems
      render('edit')
    end
  end

  def delete
    @subject=Subject.find(params[:id])
  end

  def destroy
    @subject=Subject.find(params[:id])
    @subject.destroy
    flash[:notice]="Subject '#{@subject.name}' destroyed successfully."
    redirect_to(subjects_path)
  end

  private
  def subject_params
    params.require(:subject).permit(:name,:position,:visible)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/demo/hello.html.erb
<h1>Hello world from hello!</h1>

<%= 1+1 %><br/>

<% target = "world" %>
<%= "Hello #{target}"%>

<br>
<%@array.each do |n|%>
 <%= n %> <br>
<%end%>
<br>
<%= link_to('Index page',{:action => 'index'})%> <br>

ID: <%= @id %> <br>
ID: <%= params[:id] %> <br>
Page: <%= @page %> <br>
Next page: <%= @page.to_i + <1> %>                                                                                                                                                                                                     </1> %> <br>

app/views/demo/index.html.erb
<h1>Hello world from index!</h1>

<a href="/demo/hello">hello page 1</a> <br>
<%= link_to('hello page 2',{:action => 'hello'}) %> <br>

<%= link_to('hello with parameters',{:action => 'hello',:page => 5, :id => 20}) %> <br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/delete.html.erb
<%= link_to("<<Back to list", pages_path, :class => 'back-link')%>

  <div class="pages delete">
    <h2>Delete page</h2>
    <%= form_for(@page, :method => 'delete') do |f| %>
    <p>Are you sure you want to permamently delete this page?</p>
    <p class="reference-name"> <%= f.object.name%></p>
    <div class="form-buttons">
      <%= f.submit("Delete page")%>
    </div>
  <%end%>

  </div>

app/views/pages/edit.html.erb
<%=link_to("<<Back to List", pages_path, :class=>'back-link')%>
  <div class="page edit">
    <h2>Update Page</h2>
    <%= form_for(@page) do |f|%>
    <table summary = "Pages from fields">
      <tr>
        <th>Name</th>
        <td><%= f.text_field(:name)%></td>
      </tr>
      <tr>
        <th>Position</th>
        <td><%=f.text_field(:position)%></td>
      </tr>
      <tr>
        <th>Description</th>
        <td><%= f.text_field(:description)%></td>
      </tr>
    </table>

    <div class = "form-buttons">
      <%= f.submit("Update Page")%>
    </div>
    <%end%>
      </div>

app/views/pages/index.html.erb
<% if !flash[:notice].blank?%>
<div class = "notice"></div>
<%= flash[:notice]%>
<%end%>


<div class="pages index">
  <h2>Pages</h2>

  <%= link_to("Add New Page",new_page_path, :class => 'action new') %>
  <table class ="listing" summary ="Page list">
    <tr class = "header">
      <th>#</th>
      <th>Page</th>
      <th>Position</th>
      <th>Description</th>
      <th>Actions</th>
    </tr>
    <% @pages.each do |page| %>
    <tr>
      <td><%= page.id %></td>
      <td><%= page.name %></td>
      <td class="center"><%= page.position%></td>
      <td class="center"><%= page.description %></td>
      <td class="actions">
        <%= link_to("Show", page_path(page),:class => 'action show')%>
        <%= link_to("Edit", edit_page_path(page), :class => 'action edit')%>
        <%= link_to("Delete",delete_page_path(page), :class => 'action delete')%>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/pages/new.html.erb
<%=link_to("<<Back to List", pages_path, :class=>'back-link')%>
  <div class="page new">
    <h2>Create Page</h2>
    <%= form_for(@page) do |f|%>
    <table summary = "Pages from fields">
      <tr>
        <th>Name</th>
        <td><%= f.text_field(:name)%></td>
      </tr>
      <tr>
        <th>Position</th>
        <td><%=f.text_field(:position)%></td>
      </tr>
      <tr>
        <th>description</th>
        <td><%= f.text_field(:description)%></td>
      </tr>
      <tr>
        <!-- <th>hidden</th> -->
        <td><%= f.hidden_field(:subject_id)%></td>
      </tr>
    </table>

    <div class = "form-buttons">
      <%= f.submit("Create Page")%>
    </div>
    <%end%>
      </div>

app/views/pages/show.html.erb
<% if !flash[:notice].blank?%>
<div class = "notice"></div>
<%= flash[:notice]%>
<%end%>


<%= link_to("<< Back to List", pages_path,:class => 'back-link')%>
<div class="pages show">
  <h2>Show Page</h2>

  <table summary="Page detail view">
    <tr>
      <th>Name</th>
      <td><%= @page.name%></td
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @page.position%></td>
    </tr>
    <tr>
      <th>Description</th>
      <td><%= @page.description%></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @page.created_at%></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @page.updated_at%></td>
    </tr>

  </table>
</div>

app/views/subjects/delete.html.erb
<%= link_to("<<Back to list", subjects_path, :class => 'back-link')%>

  <div class="subjects delete">
    <h2>Delete subject</h2>
    <%= form_for(@subject, :method => 'delete') do |f| %>
    <p>Are you sure you want to permamently delete this subject?</p>
    <p class="reference-name"> <%= f.object.name%></p>
    <div class="form-buttons">
      <%= f.submit("Delete subject")%>
    </div>
  <%end%>

  </div>

app/views/subjects/edit.html.erb
<%=link_to("<<Back to List", subjects_path, :class=>'back-link')%>
  <div class="subject edit">
    <h2>Update Subject</h2>
    <%= form_for(@subject) do |f|%>
    <table summary = "Subjects from fields">
      <tr>
        <th>Name</th>
        <td><%= f.text_field(:name)%></td>
      </tr>
      <tr>
        <th>Position</th>
        <td><%=f.text_field(:position)%></td>
      </tr>
      <tr>
        <th>Visible</th>
        <td><%= f.text_field(:visible)%></td>
      </tr>
    </table>

    <div class = "form-buttons">
      <%= f.submit("Update Subject")%>
    </div>
    <%end%>
      </div>

app/views/subjects/index.html.erb
<% if !flash[:notice].blank?%>
<div class = "notice"></div>
<%= flash[:notice]%>
<%end%>


<div class="subjects index">
  <h2>Subjects</h2>

  <%= link_to("Add New Subject",new_subject_path, :class => 'action new') %>
  <table class ="listing" summary ="Subject list">
    <tr class = "header">
      <th>#</th>
      <th>Subject</th>
      <th>Visible</th>
      <th>Pages</th>
      <th>Position</th>
      <th>Actions</th>
    </tr>
    <% @subjects.each do |subject| %>
    <tr>
      <td><%= subject.id %></td>
      <td><%= subject.name %></td>
      <td class="center"><%= subject.visible ? 'Yes': 'No'%></td>
      <td class="center"><%= subject.pages.size %></td>
      <td><%=subject.position%></td>
      <td class="actions">
        <%= link_to("Show", subject_path(subject),:class => 'action show')%>
        <%= link_to("Edit", edit_subject_path(subject), :class => 'action edit')%>
        <%= link_to("Delete",delete_subject_path(subject), :class => 'action delete')%>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/subjects/new.html.erb
<%=link_to("<<Back to List", subjects_path, :class=>'back-link')%>
  <div class="subject new">
    <h2>Create Subject</h2>
    <%= form_for(@subject) do |f|%>
    <table summary = "Subjects from fields">
      <tr>
        <th>Name</th>
        <td><%= f.text_field(:name)%></td>
      </tr>
      <tr>
        <th>Position</th>
        <td><%=f.text_field(:position)%></td>
      </tr>
      <tr>
        <th>Visible</th>
        <td><%= f.text_field(:visible)%></td>
      </tr>
    </table>

    <div class = "form-buttons">
      <%= f.submit("Create Subject")%>
    </div>
    <%end%>
      </div>

app/views/subjects/show.html.erb
<% if !flash[:notice].blank?%>
<div class = "notice"></div>
<%= flash[:notice]%>
<%end%>


<%= link_to("<< Back to List", subjects_path,:class => 'back-link')%>
<div class="subjects show">
  <h2>Show Subject</h2>

  <table summary="Subject detail view">
    <tr>
      <th>Name</th>
      <td><%= @subject.name%></td
    </tr>
    <tr>
      <th>Email</th>
      <td><%= @subject.email%></td>
    </tr>
    <tr>
      <th>Visible</th>
      <td><%= @subject.visible ? 'true' : 'false'%></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @subject.created_at%></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @subject.updated_at%></td>
    </tr>

  </table>
</div>